imposing-union-227917.sumo.surveygizmo_problem_solved

SELECT distinct(Did_you_accomplish_the_goal_of_your_visit_) Problem_Solved, count(Did_you_accomplish_the_goal_of_your_visit_) as count from `imposing-union-227917.sumo.surveygizmo` group by Did_you_accomplish_the_goal_of_your_visit_


imposing-union-227917.sumo.surveygizmo_csat_score

SELECT distinct(How_would_you_rate_your_experience_with_support_mozilla_org__Please_help_us_by_only_rating_the_website_and_not_Firefox_) Score, count(How_would_you_rate_your_experience_with_support_mozilla_org__Please_help_us_by_only_rating_the_website_and_not_Firefox_) as count from `imposing-union-227917.sumo.surveygizmo` group by How_would_you_rate_your_experience_with_support_mozilla_org__Please_help_us_by_only_rating_the_website_and_not_Firefox_
